### ISSUE TITLE
Typo: glogarithms

### ISSUE THREAD

**Issue by Ryuno-Ki** [Mte90/Contribute-to-opensource-the-right-way#2]
Hi Daniele!

I heed [your call](https://twitter.com/Mte90Net/status/1223324311928393735) and downloaded a PDF version from GitHub (since I don't understand Leanpub with USD at the moment).

In [your flashback](https://github.com/Mte90/Contribute-to-opensource-the-right-way/blob/068fd87b2f191e0f7782691c2fc74d6be7fd320f/manuscript/chapter1-bio.md#lets-start-with-the-flashback) you wrote:

> Something clearly impossible at that time, it was a like an elitarian job, because there was this idea that to be good at computer you needed to be good at math remembering formulas or calculating glogarithms.

Shouldn't that be algorithm? Or did you teach LanguageTool cool new words? :-)

**Comment by Mte90** [comment]
ergh should be algorithms.
On leanpub you can download it also without paying/donating, just put as amount 0.

**Comment by Ryuno-Ki** [comment]
I mean, you could also call it on purpose to highlight your … delight … of math.
