### ISSUE TITLE
Evaluate new formatting

### ISSUE THREAD

**Issue by Mte90** [Mte90/Contribute-to-opensource-the-right-way#20]
Some users reported that the font size is smaller or the font is not very good.
This ticket is to track and investigate for alternatives for this issue.

**Comment by Mte90** [comment]
http://help.leanpub.com/en/articles/582505-how-can-i-see-what-the-different-fonts-look-like-so-i-know-which-one-to-choose 

Require a paid account, it isn't a problem but the real problem is to define what font to use.

**Comment by Ryuno-Ki** [comment]
For web use a serif sans-font.
For print use a serif font.

Personally, I'm also looking for features like [Old-style numerals](https://en.wikipedia.org/wiki/Text_figures) or [slashed zeroes](https://en.wikipedia.org/wiki/Slashed_zero) or [Small caps](https://en.wikipedia.org/wiki/Small_caps).

You might want to pick a font with [ligatures](https://en.wikipedia.org/wiki/Orthographic_ligature#Stylistic_ligatures).

Perhaps also worth watching out for [ascenders and descenders](https://en.wikipedia.org/wiki/Ascender_(typography)).

Each font family also has a history. If you research it (and a bit about the creator) you might learn more about the intended use. What emotion do you want to evoke?

**Comment by Mte90** [comment]
I don't know what I want really.
I got some feedback on first edition about the font itself, but they wasn't clear at all.

**Comment by Ryuno-Ki** [comment]
Okay, let's break it down in smaller questions:
Where is the content supposed to be read?
