### ISSUE TITLE
Provide pre-release files

### ISSUE THREAD

**Issue by d1nuc0m** [Mte90/Contribute-to-opensource-the-right-way#23]
Hi, I've seen on [Reddit](https://www.reddit.com/r/opensource/comments/wfy0d8/contribute_to_opensource_the_right_way_3rd/) and LUG Sapienza that you're asking for a feedback on the new edition.
I think it would be useful to have a prebuilt pre-release (maybe tagged with the last commit, such as _2022.1_pre_2022.07.17_), so that new readers could evaluate and provide feedback about the new version without having to build it from the development branch.

**Comment by Mte90** [comment]
The pdf etc are generated with leanpub.
To do that I need the changes on the master branch so the PR requires to be merged.

In the past for the previous release I used the PR diff window and reviewer read the previous edition or used the markdown rendering by github itself without generate them.

Anyway I can generate a PDF like in #24

**Comment by Mte90** [comment]
The 3rd edition pdf [Book.pdf](https://github.com/Mte90/Contribute-to-opensource-the-right-way/files/9282871/Book.pdf)

**Comment by d1nuc0m** [comment]
> The 3rd edition pdf [Book.pdf](https://github.com/Mte90/Contribute-to-opensource-the-right-way/files/9282871/Book.pdf)

Thank you, I'll read it as soon as possible, I hope I'll be able to provide an useful feedback :)
