### ISSUE TITLE
Build how-to

### ISSUE THREAD

**Issue by d1nuc0m** [Mte90/Contribute-to-opensource-the-right-way#24]
Related to #23 
How could users build a PDF output? The[ build.sh](https://github.com/Mte90/Contribute-to-opensource-the-right-way/blob/master/tools/build.sh) uses "leanpub", but I wasn't able to understand how to install these tools

**Comment by Mte90** [comment]
You are right, as I am using leanpub to generate the official files I used this old package to generate a readable PDF https://pypi.org/project/leanpub/

It is not mentioned in the script...

**Comment by d1nuc0m** [comment]
Thank you, have you considered citing it in the script as a comment or in the readme?

**Comment by Mte90** [comment]
Link added to the script, I never mentioned because that script was just for me :-)
