### ISSUE TITLE
Proposal: switch build system to LaTeX

### ISSUE THREAD

**Issue by d1nuc0m** [Mte90/Contribute-to-opensource-the-right-way#25]
Possible solution to #20 and to the problem of generating PDFs of #23.
The leanpub Python package generates [a PDF](https://github.com/Mte90/Contribute-to-opensource-the-right-way/issues/23#issuecomment-1208250842) that in the metadata reports "_Creator: LaTeX via pandoc, Producer: pdfTeX-1.40.24_", while the PDF of the 2020.1 release reports "_Creator: LaTeX with hyperref package, Producer: XeTeX 0.99999_". 

So, as leanpub looks like a kind of wrapper for LaTeX, what about switching to LaTeX without passing trough the additional steps? It would require more work initially, but would give way more control over the final result (and if I understood correctly, leanpub.com also accepts PDFs/ePubs created externally).

**Comment by Mte90** [comment]
It is not possible.
https://leanpub.com/ service has it is own standard and this book uses it, the script it is just a way to get the PDF version manually.

https://leanpub.com/contributetoopensource-therightway/ when everything is on the master I can generate some pre release version also in mobi and other formats. I don't want to have to deal with custom layouts and so on and just focus on the content so the service will generate by the repo files the definitive ebook.
