### ISSUE TITLE
Suggestion: books and resources

### ISSUE THREAD

**Issue by d1nuc0m** [Mte90/Contribute-to-opensource-the-right-way#26]
Books that you need to read:
- [The Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) - a classic about different open software development strategies
- [Linux Foundation reading list](https://www.linuxfoundation.org/blog/ultimate-open-source-reading-list/) (broken links are usually accessible through WayBack Machine)

Other resources (maybe in a Standards/Conventions subsection?):
- [Conventional Commits](https://www.conventionalcommits.org)
- [Semantic Versioning](https://semver.org/)

Websites:
- OSPO (Open Source and Open Source Program Offices) [Guides and Resources](https://todogroup.org/guides/)

**Comment by Mte90** [comment]
I avoided the first book as I think that honestly after all this years various things are not updated anymore and also the author is actually not considered so much in the OSS.

I read it in the past other books like from Torvalds and others but the list of books I suggests are in the last chapter of the book. I wanted to put my point of view in the book and mentioned the really one you need to succeed and understand open source https://github.com/Mte90/Contribute-to-opensource-the-right-way/blob/master/manuscript/conclusion.md#books-that-you-need-to-read

Usually those resources are books with the open source story of the origin in the 80s that are not modern anymore and majority of people that want to contribute doesn't care so much.

About Commits and Versioning it isn't part of the book as it is a guide to learn how to contribute and not just focused on development, there are too many for that. I am using conventional commits anyway in my work like also semantic, but those are objective solutions.
